### ISSUE TITLE
No space left on /tmp

### ISSUE THREAD

**Issue by byee4** [YeoLab/sailor#3]
tscc-2-51.sdsc.edu 2017-04-30 23:29:01,603 MainThread WARNING toil.fileStore: Detected that job ('file:///home/bay001/processing_scripts/codebase/rna_editing_pipeline/RNA_editing_pipeline/singularity-dev/src/cwl/split_strands.cwl' split_strands.py k/n/jobUYWYZi) prematurely terminated.  Fixing the state of the cache.
Traceback (most recent call last):
  File "/home/bay001/anaconda/envs/rna-editing/bin/cwl-runner", line 11, in <module>
    sys.exit(main())
  File "/home/bay001/anaconda/envs/rna-editing/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 739, in main
    outobj = toil.start(wf1)
  File "/home/bay001/anaconda/envs/rna-editing/lib/python2.7/site-packages/toil/common.py", line 682, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/bay001/anaconda/envs/rna-editing/lib/python2.7/site-packages/toil/common.py", line 991, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/bay001/anaconda/envs/rna-editing/lib/python2.7/site-packages/toil/leader.py", line 175, in run
    self.innerLoop()
  File "/home/bay001/anaconda/envs/rna-editing/lib/python2.7/site-packages/toil/leader.py", line 437, in innerLoop
    self.processFinishedJob(jobID, result, wallTime=wallTime)
  File "/home/bay001/anaconda/envs/rna-editing/lib/python2.7/site-packages/toil/leader.py", line 739, in processFinishedJob
    self.jobStore.update(jobGraph)
  File "/home/bay001/anaconda/envs/rna-editing/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 140, in update
    pickler.dump(job, f)
IOError: [Errno 28] No space left on device

**Comment by byee4** [comment]
I think setting --cachedir to something else (not /tmp) solves this.

**Comment by YangpingLi** [comment]
I have this problem with a large bam file now. Where can I set this variable?

**Comment by byee4** [comment]
You can use the cwltool parameter --cachedir to set the working directory, otherwise there might be an environment variable (ie. export TMP_DIR=/tmp, might also be $TMPDIR or $TMP) that you might be able to set.
